apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: lucl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lucl
    app.kubernetes.io/part-of: byoc-app-jyup
  name: luclobfb
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: lucl
    weight: null
status: {}
